name: Continuous Deployment

on:
  push:
    branches: [ master ]  # Se dispara cuando haces push a la rama main
    
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Ejecutar comandos vía SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Definir el nombre del repo dinámicamente
            REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
            BASE_PATH="/home/${{ secrets.SSH_USER }}/$REPO_NAME"

            # 1. Crear carpeta si no existe y entrar
            mkdir -p $BASE_PATH && cd $BASE_PATH

            # 2. Clonar si está vacío o actualizar si ya existe
            if [ ! -d ".git" ]; then
              git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@://github.com${{ github.repository }}.git .
            else
              git pull https://x-access-token:${{ secrets.GITHUB_TOKEN }}@://github.com${{ github.repository }}.git master
            fi

            # 3. Crear el archivo .env
            echo "POSTGRES_USER=${{ secrets.DB_USER }}" > .env
            echo "POSTGRES_PASSWORD=${{ secrets.DB_PASS }}" >> .env
            echo "POSTGRES_DB=${{ secrets.DB_NAME }}" >> .env

            # 4. Levantar servicios (usando el usuario con permisos de docker)
            docker compose up -d --build
            docker image prune -f
